name: Functional Imperative
url: http://www.functionalimperative.com/
markdown: redcarpet
highlighter: pygments

# for use outside the project
keep_files:
  - ./assets/logo_mini.png
  - ./assets/Lighthouse.png

exclude: [Rakefile, README.md, Gemfile, Gemfile.lock]
paginate: 5
paginate_path: "blog/page:num"
excerpt_separator: <!--more-->
assets:
  sources:
    - _assets
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

  ##### development #####

  # debug: true
  # cachebust: hard
  # gzip: false
  # js_compressor: none
  # css_compressor: none

  ##### production  #####

  debug: true
  cachebust: none
  gzip: true
  js_compressor: uglifier
  css_compressor: yui
