name: Functional Imperative
markdown: redcarpet
highlighter: pygments

# Jekyll 3
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap

# for use outside the project
keep_files:
  - ./assets/logo_mini.png
  - ./assets/Lighthouse.png

exclude: [
  Rakefile,
  README.md,
  README-Editors.md,
  Gemfile,
  Gemfile.lock
]

paginate: 5
paginate_path: "blog/page:num"
excerpt_separator: <!--more-->

assets:
  sources:
    - _assets
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

  digest: false
  compress:
    css: false
    js: false

