name: Functional Imperative
markdown: redcarpet
highlighter: pygments

# Jekyll 3
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap

# for use outside the project
keep_files:
  - ./assets/logo_mini.png
  - ./assets/Lighthouse.png
  - ./assets/shaders/*.glsl

exclude: [
  Rakefile,
  README.md,
  README-Editors.md,
  Gemfile,
  Gemfile.lock,
  drafts
]

redcarpet:
  extensions: ["tables"]

paginate: 5
paginate_path: "custom-software-development-company-blog/page:num"
excerpt_separator: <!--more-->

permalink: "/custom-software-development-company-blog/:title.html"

assets:
  cache: false
  
  assets:
    - "*.glsl"
  
  sources:
    - _assets
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/shaders/

  digest: false
  compress:
    css: false
    js: false
    glsl: false

