name: Functional Imperative
markdown: redcarpet
highlighter: pygments
exclude: [Rakefile, README.md, Gemfile, Gemfile.lock]
paginate: 5
paginate_path: "blog/page:num"
assets: 
  debug: true
  sources:
    - _assets
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

  ##### development #####

  # cachebust: hard
  # gzip: false
  # js_compressor: none
  # css_compressor: none

  ##### production  #####

  cachebust: none
  gzip: true
  js_compressor: uglifier
  css_compressor: yui
